### ISSUE TITLE
Error 500 on /api/v1/contacts/${contact_id}

### ISSUE THREAD

**Issue by ncoden** [CaliOpen/caliopen.api.user#5]
Error 500 on /api/v1/contacts/${contact_id}
For exemple : /api/v1/contacts/687bc3fd-77ba-490f-aca5-eb2e21dcfc76

```
api_1  | 2016-03-02 21:33:42,628 DEBUG [caliopen.api.user.authentication][waitress] Authentication via Access Token
api_1  | 2016-03-02 21:33:42,644 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/687bc3fd-77ba-490f-aca5-eb2e21dcfc76
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
api_1  |     task.service()
api_1  |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
api_1  |     self.execute()
api_1  |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
api_1  |     app_iter = self.channel.server.application(env, start_response)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1  |     response = self.invoke_subrequest(request, use_tweens=True)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1  |     response = handle_request(request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1  |     response = view_callable(exc, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1  |     result = view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1  |     response = handler(request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1  |     response = view_callable(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1  |     return view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1  |     return view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1  |     return view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1  |     return view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1  |     result = view(context, request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1  |     response = view(request)
api_1  |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1  |     response = view_()
api_1  |   File "/usr/local/lib/python2.7/dist-packages/caliopen/api/user/contact.py", line 55, in get
api_1  |     return {'contacts': ReturnContact.build(contact).serialize()}
api_1  |   File "/usr/local/lib/python2.7/dist-packages/caliopen/base/parameters.py", line 44, in build
api_1  |     attr = [x.to_dict() for x in attr]
api_1  | AttributeError: 'str' object has no attribute 'to_dict'
web_1  | GET /api/v1/contacts/687bc3fd-77ba-490f-aca5-eb2e21dcfc76 500 25.275 ms - 110
```

**Comment by gdchamal** [comment]
working on a fix, should be ok within this day
